version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./:/app          
      - /app/node_modules     
    environment:
      - CHOKIDAR_USEPOLLING=true  
      - WATCHPACK_POLLING=true     